Cache current context before creating a new user
Somehow, the fragment can get detached for a short amount of time
when the UserManagerService decides to create a new user. This is
bad because it needs the fragment context to generate the default
icon. Thus, this can lead to a race between generating icon and
reattaching the fragment, bring in randomly freeze caused by the
following exception.

java.lang.IllegalStateException: Fragment UserSettings{5995c0c} (7bbe2153-a754-4b1e-b629-f4c006d4a8d3)} not attached to a context.
 	at androidx.fragment.app.Fragment.requireContext(Fragment.java:901)
 	at androidx.fragment.app.Fragment.getResources(Fragment.java:965)

Cache the context before using to workaround this issue.

Change-Id: I56c31433a2481da6d2595cf709143f838e50d5c1
Signed-off-by: LibXZR <i@xzr.moe>
Signed-off-by: Joey Huab <joey@evolution-x.org>